#!/bin/bash

# ./runall [-r rounds] [-p threads] [-l]

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

export THREADS=`nproc --all`
export ROUNDS=3
export ARGS="./runall [-r rounds] [-p threads]"
while getopts ":p:r:l" option
do
        case "${option}"
        in
          r) ROUNDS=$OPTARG;;
          p) THREADS=$OPTARG;;
          l) LARGE=1;;
          \?) echo $ARGS >&2; exit 1;;
          :)  echo $ARGS >&2; exit 1;;
        esac
done

date
if [ $LARGE ]
then
    echo "including large inputs"
fi
echo threads=$THREADS
echo rounds=$ROUNDS
export CILK_NWORKERS=$THREADS

head="numactl -i all"
if [ $THREADS == 1 ]
then
    head=""
fi

# make clean
make aug_sum

echo
printf "${RED}With augmentation${NC}\n"
# union
$head ./aug_sum -r $ROUNDS -n 100000000 -m 100000000 0
$head ./aug_sum -r $ROUNDS -n 100000000 -m 100000 0

# find
$head ./aug_sum -r $ROUNDS -n 100000000 -m 100000000 12

# insert
if [ $THREADS == 1 ]
then
$head ./aug_sum -r $ROUNDS -n 100000000 20
fi

# fromseq
$head ./aug_sum -r $ROUNDS -n 100000000 4


# filter
$head ./aug_sum -r $ROUNDS -n 100000000 5

# multi insert
$head ./aug_sum -r $ROUNDS -n 100000000 -m 100000000 14
$head ./aug_sum -r $ROUNDS -n 100000000 -m 100000 14

# range
$head ./aug_sum -r $ROUNDS -n 100000000 -m 10000000 18

# aug left
$head ./aug_sum -r $ROUNDS -n 100000000 -m 100000000 22

# aug range
$head ./aug_sum -r $ROUNDS -n 100000000 -m 100000000 19

make aug_sumNA

echo
printf "${RED}Without augmentation${NC}\n"
# union
$head ./aug_sumNA -r $ROUNDS -n 100000000 -m 100000000 0

# insert
if [ $THREADS == 1 ]
then
    $head ./aug_sumNA -r $ROUNDS -n 100000000 20
fi

# fromseq
$head ./aug_sumNA -r $ROUNDS -n 100000000 4

# range
$head ./aug_sumNA -r $ROUNDS -n 100000000 -m 10000000 18

# STL

if [ $THREADS == 1 ]
then
    
# tree union
$head ./aug_sumNA -r $ROUNDS -n 100000000 -m 100000000 10
$head ./aug_sumNA -r $ROUNDS -n 100000000 -m 100000 10

# vector union
$head ./aug_sumNA -r $ROUNDS -n 100000000 -m 100000000 11
$head ./aug_sumNA -r $ROUNDS -n 100000000 -m 100000 11

# insert
$head ./aug_sumNA -r $ROUNDS -n 100000000 16
fi

# Large inputs

echo
printf "${RED}Large input${NC}\n"
if [ $LARGE ]
then
    $head ./aug_sum -r $ROUNDS -n 10000000000 4
    $head ./aug_sum -r $ROUNDS -n 10000000000 -m 100000000 19
fi
